Use more modern SBT to fix binary compatibility problems
Building Forge on my system triggered because of (I assume) a binary
compatibility error in SBT (pasted below), probably due to some global
plugin compiled for 0.12.x running into some binary compatibility
change with 0.12.0-Beta2. Upgrading to 0.12.0 fixes the issue, so
here's the patch.

[info] Compiling 27 Scala sources to /Users/pgiarrusso/Documents/Research/Sorgenti/Forge/target/scala-2.10/classes...
[error] {file:/Users/pgiarrusso/Documents/Research/Sorgenti/Forge/}Forge/compile:compile: java.lang.NoSuchMethodError: xsbti.api.Modifiers.<init>(ZZZZZZ)V
[error] Total time: 21 s, completed Feb 11, 2013 9:04:28 PM